default_platform :android

platform :android do
  before_all do
    # gradle(task: 'clean')
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  lane :setup_for_ci do
    Dir.chdir('..') do
      sh('echo $GOOGLE_SERVICES_JSON > app/google-services.json')
    end
  end

  desc "Build an aab"
  lane :build do
    gradle(task: "bundleDebug")
  end

  desc "Run unit tests"
  lane :test do
    gradle(task: "testDebugUnitTest")
  end

  lane :debugbuild do
    gradle(task: 'assembleDebug')
  end

  lane :bundle_release do
    gradle(task: 'bundleRelease')
  end

  # To upload an aab, needs to link Google Play Account to your Firebase project, so upload an apk currently
  lane :deploy_to_firebase_app_distribution do
    gradle(task: "assembleDebug")
    sh(
      'firebase',
      'appdistribution:distribute',
      '../app/build/outputs/apk/debug/app-debug.apk',
      '--app',
      ENV['FIREBASE_APP_ID'],
      '--release-notes-file',
      '../release_notes.txt',
      '--groups',
      'tester'
    )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
