name: Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}
  cancel-in-progress: true

env:
  FASTLANE_HIDE_CHANGELOG: true
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -XX:+UseParallelGC -XX:MaxMetaspaceSize=2g"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17
    - name: Cache gradle dir
      uses: actions/cache@v3
      if: ${{ !startsWith(github.head_ref, 'dependabot') }}
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build with Gradle
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        bundle exec fastlane android setup_for_ci
        bundle exec fastlane android build
