name: Build

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || 'develop' }}
  cancel-in-progress: true

env:
  FASTLANE_HIDE_CHANGELOG: true
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx6g -XX:+UseParallelGC -XX:MaxMetaspaceSize=2g"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
    - name: Cache gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/wrapper
        key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
    - name: Cache dependencies
      uses: actions/cache@v4
      if: ${{ !startsWith(github.head_ref, 'dependabot') }}
      with:
        path: |
          ~/.gradle/caches/jars-*
          ~/.gradle/caches/modules-*
          ~/.gradle/caches/transforms-*
        key: gradle-dependencies-${{ hashFiles('gradle/libs.versions.toml') }}
        restore-keys: |
          gradle-dependencies-
    - name: Cache build results
      uses: actions/cache@v4
      with:
        path: |
          .gradle
          ~/.gradle/caches/build-cache-*
          ~/.gradle/caches/[0-9]*.* # TODO: specify latest only
        key: gradle-build-cache-${{ github.sha }}
        restore-keys: gradle-build-cache-
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Build with Gradle
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      run: |
        bundle exec fastlane android setup_for_ci
        bundle exec fastlane android build
